# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 16:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('simplecontent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 17, 16, 47, 40, 311089, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='modefied',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 17, 16, 47, 50, 391134, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
