# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 15:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('simplecontent', '0002_auto_20160517_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='current',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 5, 18, 15, 8, 9, 32792, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
